export const RouteNavList = {
	managers: () => '/managers',
	applications: () => '/applications',
	search: () => '/search',
	brand: () => '/brand',
	banner: () => '/banner',
	withdraws: () => '/withdraws',
	supplies: () => '/supplies',
	history: () => '/history',
	order: () => '/order',
	list: () => '/list',
	notfound: () => '/notfound',
	catalog: () => '/catalog',
	vendor: () => '/vendor/:id',
	security: () => '/security',
}

export const RoutePathList = {
	managers: '/managers',
	search: '/search',
	supplies: '/supplies',
	applications: '/applications',
	history: '/history',
	brand: '/brand',
	banner: '/banner',
	auth: '/auth',
	order: '/order',
	notfound: '/notfound',
	product: '/product/:id',
	list: '/list',
	withdraws: '/withdraws',
	security: '/security',
	catalog: '/catalog',
	vendor: '/vendor/:id',
}
