export const RouteNavList = {
  managers: () => '/managers',
  applications: () => '/applications',
  search: () => '/search',
  brand: () => '/brand',
  banner: () => '/banner',
  withdraws: () => '/withdraws',
  paymentRequest: () => '/paymentRequest',
  logs: () => '/logs',
  supplies: () => '/supplies',
  history: () => '/history',
  order: () => '/order',
  orders: () => '/orders',
  list: () => '/list',
  notfound: () => '/notfound',
  catalog: () => '/catalog',
  vendor: () => '/vendor/:id',
  users: () => '/users',
}

export const RoutePathList = {
  managers: '/managers',
  search: '/search',
  supplies: '/supplies',
  paymentRequest: '/paymentRequest',
  applications: '/applications',
  history: '/history',
  brand: '/brand',
  banner: '/banner',
  logs: '/logs',
  auth: '/auth',
  order: '/order',
  orders: '/orders',
  notfound: '/notfound',
  product: '/product/:id',
  list: '/list',
  withdraws: '/withdraws',
  users: '/users',
  catalog: '/catalog',
  vendor: '/vendor/:id',
}
